name: genesis_robotec
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  rxdart: ^0.27.7
  overlay_support: ^2.1.0
  package_info_plus: ^3.0.2
  connectivity_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  # android: true
  # ios: true
  # web: true
  # color: "#005f27"
  # image: assets/launcher/splash.png
  # android_12:
  #   image: assets/launcher/splash.png
  #   icon_background_color: "#005f27"

flutter_icons:
  # android: true
  # ios: true
  # image_path_ios: "assets/launcher/ios.png"
  # image_path_android: "assets/launcher/android.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
