// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlE_avsrXlTdxss2QrFPjcbJZ75o821I',
    appId: '1:231699862816:web:1fc686a561dd9ab0253345',
    messagingSenderId: '231699862816',
    projectId: 'genesis-robotec',
    authDomain: 'genesis-robotec.firebaseapp.com',
    storageBucket: 'genesis-robotec.appspot.com',
    measurementId: 'G-E376L4K0Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLL0ZMpdUKQB-Ssl9Uz49Ea0Pbb8SVPo',
    appId: '1:231699862816:android:1c3b2703c19bcbda253345',
    messagingSenderId: '231699862816',
    projectId: 'genesis-robotec',
    storageBucket: 'genesis-robotec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uj3OCKBV2DLsQt_QWskdCXfH5rFlbTY',
    appId: '1:231699862816:ios:9a8bd5c691147c0b253345',
    messagingSenderId: '231699862816',
    projectId: 'genesis-robotec',
    storageBucket: 'genesis-robotec.appspot.com',
    iosClientId: '231699862816-1pa9nsmgpmnnj5ku4qup021k2e54s3fl.apps.googleusercontent.com',
    iosBundleId: 'com.genesisrobotec.app',
  );
}
